// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, Client, TDataShape } from './client';
import type { IndexData, IndexResponses, CreateData, CreateResponses, CreateErrors, Index2Data, Index2Responses, Index2Errors } from './types.gen';
import { client } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const index = <ThrowOnError extends boolean = false>(options?: Options<IndexData, ThrowOnError>) => {
    return (options?.client ?? client).get<IndexResponses, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

export const create = <ThrowOnError extends boolean = false>(options: Options<CreateData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateResponses, CreateErrors, ThrowOnError>({
        url: '/software/create',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const index2 = <ThrowOnError extends boolean = false>(options?: Options<Index2Data, ThrowOnError>) => {
    return (options?.client ?? client).get<Index2Responses, Index2Errors, ThrowOnError>({
        url: '/software/index',
        ...options
    });
};
