// This file is auto-generated by @hey-api/openapi-ts

export type BackendError = {
    message: string;
};

export type SoftwareTool = {
    image_links: Array<string>;
    long_desc: string;
    name: string;
    short_desc: string;
    web_link: string;
};

export type IndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type IndexResponses = {
    200: string;
};

export type IndexResponse = IndexResponses[keyof IndexResponses];

export type CreateData = {
    body: SoftwareTool;
    path?: never;
    query?: never;
    url: '/software/create';
};

export type CreateErrors = {
    500: BackendError;
};

export type CreateError = CreateErrors[keyof CreateErrors];

export type CreateResponses = {
    200: SoftwareTool;
};

export type CreateResponse = CreateResponses[keyof CreateResponses];

export type Index2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/software/index';
};

export type Index2Errors = {
    500: BackendError;
};

export type Index2Error = Index2Errors[keyof Index2Errors];

export type Index2Responses = {
    200: Array<SoftwareTool>;
};

export type Index2Response = Index2Responses[keyof Index2Responses];

export type ClientOptions = {
    baseUrl: 'http://localhost.:5000' | (string & {});
};
