[package]
name = "frontend"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/callumadair/callumadair.github.io"
description = "My lil personal web app for technology trialling."
readme = "../README.md"
keywords = ["web", "fullstack"]
categories = ["web-programming", "gui"]

[dependencies]
capitalize.workspace = true
components.workspace = true
gloo.workspace = true
lucide-yew.workspace = true
serde.workspace = true
shared.workspace = true
strum.workspace = true
yew.workspace = true
yew-router.workspace = true

[lints]
workspace = true

[workspace]
members = ["components"]

[workspace.dependencies]
capitalize = "0.3.4"
components = { path = "components" }
chrono = "0.4.39"
gloo = "0.11.0"
lucide-yew = "1.1.0"
serde = { version = "1.0.217", features = ["derive"] }
shared = { path = "../shared" }
strum = { version = "0.26.3", features = ["derive"] }
web-sys = { version = "0.3.76", features = ["HtmlDialogElement"] }
yew = { version = "0.21.0", features = ["csr"] }
yew-router = "0.18.0"

[workspace.lints.rust]
warnings = "warn"
deprecated-safe = "warn"
future-incompatible = "warn"
keyword-idents = "warn"
let-underscore = "warn"
nonstandard-style = "warn"
refining-impl-trait = "warn"
rust-2024-compatibility = "warn"
unused = "warn"

[workspace.lints.clippy]
correctness = "warn"
suspicious = "warn"
complexity = "warn"
perf = "warn"
style = "warn"
pedantic = "warn"
cargo = "warn"
