[package]
name = "frontend"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/callumadair/callumadair.github.io"
description = "My lil personal web app for technology trialling."
readme = "../README.md"
keywords = ["web", "fullstack"]
categories = ["web-programming", "gui"]

[dependencies]
capitalize.workspace = true
gloo.workspace = true
lucide-yew.workspace = true
serde.workspace = true
shared.workspace = true
strum.workspace = true
yew.workspace = true
yew-router.workspace = true

[lints]
workspace = true