[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/"
filehash = true
inject_scripts = true


[serve]
addresses = ["::1", "0.0.0.0"]
port = 3000

[tools]
tailwindcss = "4.0.7"

[watch]
watch = [".", "../shared"]