[workspace]
members = ["backend", "frontend", "shared", "shared/shared_macros", "backend/migration", "backend/entity"]
resolver = "2"

[workspace.dependencies]
dioxus = { version = "0.6.3", features = ["router", "web"] }
gloo = "0.11.0"
lucide-dioxus = "1.1.0"
serde = { version = "1.0.217", features = ["derive"] }
shared = { path = "./shared" }
strum = { version = "0.26.3", features = ["derive"] }
thiserror = { version = "2.0.11" }

[workspace.lints.rust]
warnings = "warn"
deprecated-safe = "warn"
future-incompatible = "warn"
keyword-idents = "warn"
let-underscore = "warn"
nonstandard-style = "warn"
refining-impl-trait = "warn"
rust-2024-compatibility = "warn"
unused = "warn"

[workspace.lints.clippy]
correctness = "warn"
suspicious = "warn"
complexity = "warn"
perf = "warn"
style = "warn"
pedantic = "warn"
cargo = "warn"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
