services:
  dev-server:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile

    command: trunk serve
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: /portfolio-web-app
          target: ./
          ignore:
            - backend
            - node_modules
            - target
            - dist

  dev-backend:
    build: ./backend
    command: cargo run
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: /backend
          target: ./backend
          ignore:
            - ./backend/target

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"