services:
  dev-server:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile

    command: trunk serve
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: rebuild
          path: .
          target: /frontend-workspace
          ignore:
            - ./frontend/node_modules/
            - ./frontend/target/
            - ./frontend/dist/

  dev-backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: cargo run
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: rebuild
          path: .
          target: /backend-workspace
          ignore:
            - ./backend/target/

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"