/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./index.html", "./src/**/*.rs"],
    theme: {
        extend: {},
    },
    plugins: [
        require('daisyui'),
        require('@tailwindcss/forms')({
            strategy: 'base',
            strategy: 'class',
        }),
        require('@tailwindcss/typography'),
        require('@tailwindcss/container-queries'),
        require('tailwindcss-animate'),
        require('tailwindcss-opentype'),
    ],

    daisyui: {
        themes: [
            {
                lakeview: {
                    ...require("daisyui/src/theming/themes")["emerald"],
                    "primary": "#54627B",
                    "primary-content": "#FFFFFF",
                    "secondary": "#ECD5BB",
                    "secondary-content": "#FFFFFF",
                    "accent": "#710777",
                    "accent-content": "#FFFFFF",
                }
            },

            "light",
            "dark",
            "cupcake",
            "bumblebee",
            "emerald",
            "corporate",
            "synthwave",
            "retro",
            "cyberpunk",
            "valentine",
            "halloween",
            "garden",
            "forest",
            "aqua",
            "lofi",
            "pastel",
            "fantasy",
            "wireframe",
            "black",
            "luxury",
            "dracula",
            "cmyk",
            "autumn",
            "business",
            "acid",
            "lemonade",
            "night",
            "coffee",
            "winter",
            "dim",
            "nord",
            "sunset",
        ],
        darkTheme: "dark",
        base: true,
        styled: true,
        utils: true,
        prefix: "",
        logs: true,
        themeRoot: ":root",
    },
}

