stages:
  - check
  - test
  - build

.rust:
  cache:
    - key:
        files:
          - backend/Cargo.lock
      paths:
        - backend/target
  image: "callumadair/portfolio-backend:latest"
  variables:
    BACKEND_DIR: "./backend"
    FF_USE_FASTZIP: "true"
    CACHE_COMPRESSION_LEVEL: "fastest"
  before_script:
    - cd $BACKEND_DIR

clippy:
  extends: .rust
  stage: check
  script:
    - cargo clippy

rustfmt:
  extends: .rust
  stage: check
  script:
    - cargo +nightly fmt --check

llvm-nextest:
  extends: .rust
  stage: test
  # this uses region for coverage summary
  coverage: '/TOTAL\s+(\d+\s+)+(\d+\.\d+\%)/'
  script:
    - cargo llvm-cov nextest
    - cargo llvm-cov report --cobertura --output-path cobertura.xml
  artifacts:
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml

cargo-build:
  extends: .rust
  stage: build
  script:
    - cargo build
