[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-settings = "0.8.0"
actix-web = { version = "4.9.0", features = ["rustls"] }
sea-orm = { version = "1.1.4", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
tokio = "1.43.0"
tracing = "0.1.41"
tracing-actix-web = "0.7.15"

[lints]
workspace = true
