[package]
name = "backend"
version = "0.1.0"
authors = ["Callum Adair"]
rust-version = "1.85.0"
edition = "2024"
description = "The parent crate for all the backend HTTP web server."
readme = "README.md"
repository = "https://github.com/callumadair/callumadair.github.io/tree/stable/backend"
license = "MIT"
workspace = ".."

[lib]
path = "./src/lib.rs"
name = "portfolio_backend_lib"

[[bin]]
path = "./src/main.rs"
name = "portfolio_backend_bin"

[dependencies]
actix-settings = { version = "0.8.0" }
actix-web = { version = "4.9.0", features = ["rustls"] }
sea-orm = { version = "1.1.4", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "with-chrono", "with-json"] }
strum.workspace = true
thiserror.workspace = true
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros"] }
tracing.workspace = true
tracing-actix-web = { version = "0.7.15" }
tracing-subscriber.workspace = true
utoipa = { version = "5.3.1", features = ["actix_extras"] }
utoipa-actix-web = { version = "0.1.2" }
utoipa-swagger-ui = { version = "9.0.0", features = ["actix-web", "debug-embed"] }

[lints]
workspace = true

[features]
default = []