[package]
name = "components"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/callumadair/callumadair.github.io"
readme = "README.md"
keywords = ["components", "yew"]
description = "Yew Component library based on daisyui for my portfolio site."
categories = ["gui", "web-programming"]

[dependencies]
chrono.workspace = true
gloo.workspace = true
lucide-yew.workspace = true
shared.workspace = true
web-sys.workspace = true
yew.workspace = true
yew-router.workspace = true

[lints]
workspace = true
