[package]
name = "shared"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/callumadair/callumadair.github.io"
readme = "README.md"
keywords = ["Types"]
description = "Shared types and functions for doing things on both the frontend and backend."
categories = ["web-programming"]

[dependencies]
chrono = "0.4.39"
gloo = "0.11.0"
lucide-yew = "1.1.0"
serde = { version = "1.0.217", features = ["derive"] }
web-sys = { version = "0.3.76", features = ["HtmlDialogElement"] }
yew = { version = "0.21.0", features = ["csr"] }
yew-router = "0.18.0"

[lints]
workspace = true

