[package]
name = "shared"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/callumadair/callumadair.github.io"
readme = "README.md"
keywords = ["Types"]
description = "Shared types and functions for doing things on both the frontend and backend."
categories = ["web-programming"]

[dependencies]
chrono = "0.4.39"
derive_more = { version = "2.0.1", features = ["display"] }
dioxus.workspace = true
gloo = "0.11.0"
lucide-dioxus.workspace = true
serde.workspace = true
strum.workspace = true
web-sys = { version = "0.3.76", features = ["KeyboardEvent", "HtmlDialogElement"] }

[lints]
workspace = true

[features]
default = ["web"]
web = ["dioxus/web", "dioxus/router"]
