name: Rust

on:
  push:
    branches: [ "convert-to-dioxus" ]
  pull_request:
    branches: [ "convert-to-dioxus" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Lint:
    runs-on: ubuntu-latest
    container: callumadair/rust-runner-image:latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: cargo clippy --workspace --all-features
