name: Rust

on:
  push:
    branches: [ "convert-to-dioxus" ]
  pull_request:
    branches: [ "convert-to-dioxus" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Lint:
    runs-on: ubuntu-latest
    container: callumadair/rust-runner-image:latest
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4
      - name: Run clippy across the workspace to check for any issues with all feature flags.
        run: cargo clippy --workspace --all-features --all-targets --no-deps

  Fmt:
    runs-on: ubuntu-latest
    container: callumadair/rust-runner-image:latest
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4
      - name: Check the formatting of all rust files.
        run: cargo +nightly fmt --check

  Test-Backend:
    runs-on: ubuntu-latest
    container: callumadair/rust-runner-image:latest
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4
      - name: Generate code coverage
        working-directory: ./backend
        run: cargo llvm-cov --all-features --cobertura --output-path cov.xml

  Test-Frontend:
    runs-on: ubuntu-latest
    container: callumadair/rust-runner-image:latest
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4
      - name: Generate code coverage
        working-directory: ./frontend
        run: cargo llvm-cov --all-features --cobertura --output-path cov.xml

  Build-Backend:
    runs-on: ubuntu-latest
    container: callumadair/portfolio-backend:latest
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4
      - name: Create a release build of the HTTP backend server
        working-directory: ./backend
        run: cargo build --release

  Build-Frontend:
    runs-on: ubuntu-latest
    container: callumadair/portfolio-frontend:latest
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4
      - name: Create a release build of the Dioxus frontend.
        working-directory: ./frontend
        run: dx build --release

